# Assignment-1: Transformations and representations

Team Name: Vision 

Roll number: 2021701002, 2021702011

# Instructions

- Code must be written in Python in Jupyter Notebooks. We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. See `Set Up` for detailed step-by-step instructions about the installation setup.
- Save all your results in ```results/<question_number>/<sub_topic_number>/```
- The **References** section provides you with important resources to solve the assignment.
- For this assignment, you will be using Open3D extensively. Refer to [Open3D Documentation](http://www.open3d.org/docs/release/): you can use the in-built methods and **unless explicitly mentioned**, don't need to code from scratch for this assignment. 
- Make sure your code is modular since you may need to reuse parts for future assignments.
- Answer the descriptive questions in your own words with context & clarity. Do not copy answers from online resources or lecture notes.
- The **deadline** for this assignment is on 11/09/2021 at 11:55pm. Please note that there will be no extensions.
- Plagiarism is **strictly prohibited**.


# Submission Instructions

1. Make sure your code runs without any errors after reinitializing the kernel and removing all saved variables.
2. After completing your code and saving your results, zip the folder with name as ``Team_<team_name>_MR2021_Assignment_<assignment_number>.zip``

# Set Up

We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. All assignments will be python based, hence familiarising yourself with Python is essential.


## Setting up Anaconda environment (Recommended)

1. Install Anaconda or Miniconda from [here](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) depending on your requirements.
2. Now simply run `conda env create -f environment.yml` in the current folder to create an environment `mr_assignment1` (`environment.yml` can be found in `misc/`).
3. Activate it using `conda activate mr_assignment1`.

## Setting up Virtual environment using venv

You can also set up a virtual environment using venv

1. Run `sudo apt-get install python3-venv` from command line.
2. `python3 -m venv ~/virtual_env/mr_assignment1`. (you can set the environment path to anything)
3. `source ~/virtual_env/mr_assignment1/bin/activate`
4. `pip3 install -r requirements.txt` from the current folder (`requirements.txt` can be found in `misc/`).

In [1]:
import open3d as o3d
import numpy as np

# 1. Getting started with Open3D

Open3D is an open-source library that deals with 3D data, such as point clouds, mesh. We'll be using Open3D frequently as we work with point clouds. Let's start with something simple:

<img src="misc/bunny.jpg" alt="drawing" width="200"/>

1. Read the Stanford Bunny file (in `data/`) given to you and visualise it using Open3D.

In [2]:
bunny_mesh = o3d.io.read_triangle_mesh("data/bunny.ply")
print(bunny_mesh)
o3d.visualization.draw_geometries([bunny_mesh])

TriangleMesh with 35947 points and 69451 triangles.


2. Convert the mesh to a point cloud and change the colour of points.

In [3]:
bunny_point_cloud = bunny_mesh.sample_points_uniformly(number_of_points = 10000)
bunny_point_cloud.paint_uniform_color([0.5, 0, 0.5])
o3d.visualization.draw_geometries([bunny_point_cloud])

3. Set a predefined viewing angle (using Open3D) for visualization and display the axes while plotting.

In [4]:
lookat = [-0.016834371241827677, 0.11011230157594104, -0.0014248118885969614]
front = [-0.67881530318456684, 0.12887841581318496, 0.72291087839368451]
up = [0.094796198629254091, 0.99162001245616449, -0.08776919517620857]

In [5]:
frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size = 0.2)

o3d.visualization.draw_geometries([frame, bunny_point_cloud], front = front, lookat = lookat, up = up, zoom = 0.7)

4. Scale, Transform, and Rotate the rabbit (visualise after each step).

In [6]:
import copy

In [7]:
# Scale about bunny's center
bunny_scaled = copy.deepcopy(bunny_point_cloud).scale(1.5, center = bunny_point_cloud.get_center())
bunny_scaled.paint_uniform_color([0.68, 0.85, 0.9])
o3d.visualization.draw_geometries([frame, bunny_point_cloud, bunny_scaled],front = front, lookat = lookat, up = up, zoom = 0.7)
o3d.io.write_point_cloud("results/1/4/bunny_scaled_center.pcd", bunny_scaled)

True

In [8]:
# Scale about origin
bunny_scaled = copy.deepcopy(bunny_point_cloud).scale(1.5, center = [0,0,0])
bunny_scaled.paint_uniform_color([0.68, 0.85, 0.9])
o3d.visualization.draw_geometries([frame, bunny_point_cloud, bunny_scaled], front = front, lookat = lookat, up = up, zoom = 0.7)
o3d.io.write_point_cloud("results/1/4/bunny_scaled_origin.pcd", bunny_scaled)

True

In [9]:
# Translate
bunny_translated = copy.deepcopy(bunny_point_cloud).translate([-0.1,0.1,-0.1])
bunny_translated.paint_uniform_color([0.68, 0.85, 0.9])
o3d.visualization.draw_geometries([frame, bunny_point_cloud, bunny_translated],front = front,lookat = lookat,up = up,zoom = 0.7)
o3d.io.write_point_cloud("results/1/4/bunny_translated.pcd", bunny_translated)

True

In [10]:
# Rotate about bunny's center
bunny_rotated = copy.deepcopy(bunny_point_cloud)
R = bunny_point_cloud.get_rotation_matrix_from_xyz((np.pi / 4, np.pi / 4, np.pi / 4))
bunny_rotated.rotate(R, center = bunny_point_cloud.get_center())
bunny_rotated.paint_uniform_color([0.68, 0.85, 0.9])
o3d.visualization.draw_geometries([frame, bunny_point_cloud, bunny_rotated],front = front, lookat = lookat, up = up, zoom = 0.7)
o3d.io.write_point_cloud("results/1/4/bunny_rotated_center.pcd", bunny_rotated)

True

In [11]:
# Rotate about origin
bunny_rotated = copy.deepcopy(bunny_point_cloud)
R = bunny_point_cloud.get_rotation_matrix_from_xyz((np.pi / 4, np.pi / 4, np.pi / 4))
bunny_rotated.rotate(R, center=[0,0,0])
bunny_rotated.paint_uniform_color([0.68, 0.85, 0.9])
o3d.visualization.draw_geometries([frame, bunny_point_cloud, bunny_rotated],front = front, lookat = lookat, up = up, zoom = 0.7)
o3d.io.write_point_cloud("results/1/4/bunny_rotated_origin.pcd", bunny_rotated)

True

5. Save the point cloud as bunny.pcd.

In [12]:
o3d.io.write_point_cloud("results/1/5/bunny.pcd", bunny_point_cloud)

True

# 2. Transformations and representations

## a) Euler angles
1. Write a function that returns a rotation matrix given the angles $\alpha$, $\beta$, and $\gamma$ in radians (X-Y-Z)

In [13]:
def rotation_matrix(alpha, beta, gamma):
    cos_alpha = np.cos(alpha)
    sin_alpha = np.sin(alpha)
    
    cos_beta = np.cos(beta)
    sin_beta = np.sin(beta)
    
    cos_gamma = np.cos(gamma)
    sin_gamma = np.sin(gamma)
    
    Rx_alpha = np.array([[1, 0, 0],
                         [0, cos_alpha, -sin_alpha],
                         [0, sin_alpha, cos_alpha]])
    
    Ry_beta = np.array([[cos_beta, 0, sin_beta],
                        [0, 1, 0],
                        [-sin_beta, 0, cos_beta]])
    
    Rz_gamma = np.array([[cos_gamma, -sin_gamma, 0],
                         [sin_gamma, cos_gamma, 0],
                         [0, 0, 1]])
    
    return np.dot(Rx_alpha, np.dot(Ry_beta, Rz_gamma))

# Rx(alpha) * Ry(beta) * Rz(gamma) => xyz

In [14]:
print(rotation_matrix(np.pi/3, np.pi/4, np.pi/6))

[[ 0.61237244 -0.35355339  0.70710678]
 [ 0.78033009  0.12682648 -0.61237244]
 [ 0.12682648  0.9267767   0.35355339]]


In [15]:
R = bunny_point_cloud.get_rotation_matrix_from_xyz((np.pi/3, np.pi/4, np.pi/6))
print(R)

[[ 0.61237244 -0.35355339  0.70710678]
 [ 0.78033009  0.12682648 -0.61237244]
 [ 0.12682648  0.9267767   0.35355339]]


2. Solve for angles using ```fsolve from scipy``` for three initializations of your choice and compare.
$$M(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0.26200263 & -0.19674724 & 0.944799 \\0.21984631 & 0.96542533 & 0.14007684 \\
    -0.93969262 & 0.17101007 & 0.29619813\end{array}\right] 
$$

In [16]:
from scipy.optimize import fsolve

In [17]:
M = np.array([[0.26200263, -0.19674724, 0.944799],
              [0.21984631, 0.96542533, 0.14007684],
              [-0.93969262, 0.17101007, 0.29619813]])

def func_solve_M(angles):
#     P = np.array([[1],[1],[1]])
    zero_matrix = (rotation_matrix(angles[0], angles[1], angles[2]) - M)
    return [zero_matrix[1][1], zero_matrix[2][0], zero_matrix[1][2]]

In [18]:
solution1_M = fsolve(func_solve_M, [1,1,1])
solution2_M = fsolve(func_solve_M, [-1, -1, -1])
solution3_M = fsolve(func_solve_M, [0, 2, 4])
print(solution1_M)
print(solution2_M)
print(solution3_M)

[-0.44174664  1.23698061  0.6441    ]
[12.02955935  1.29334074 25.42867557]
[0.44174664 1.90461205 5.63908531]


In [19]:
print("\n", rotation_matrix(solution1_M[0], solution1_M[1], solution1_M[2]))
print(np.isclose(M, rotation_matrix(solution1_M[0], solution1_M[1], solution1_M[2])))

print("\n", rotation_matrix(solution2_M[0], solution2_M[1], solution2_M[2]))
print(np.isclose(M, rotation_matrix(solution2_M[0], solution2_M[1], solution2_M[2])))

print("\n ", rotation_matrix(solution3_M[0], solution3_M[1], solution3_M[2]))
print(np.isclose(M, rotation_matrix(solution3_M[0], solution3_M[1], solution3_M[2])))


 [[ 0.26200261 -0.19674724  0.944799  ]
 [ 0.21984634  0.96542533  0.14007684]
 [-0.93969262  0.1710101   0.29619812]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

 [[ 0.26200261 -0.07988122  0.96175549]
 [-0.21984634  0.96542533  0.14007684]
 [-0.93969262 -0.24813892  0.23538236]]
[[ True False False]
 [False  True  True]
 [ True False False]]

  [[-0.26200261 -0.19674724  0.944799  ]
 [-0.21984634  0.96542533  0.14007684]
 [-0.93969262 -0.1710101  -0.29619812]]
[[False  True  True]
 [False  True  True]
 [ True False False]]


Initializing $\alpha$, $\beta$, and $\gamma$ to 1,1,1 gives the best solution for M as 0.69813179, 1.22173047, 0.52359887

$$N(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0 & -0.173648178 &  0.984807753 \\0 & 0.984807753 & 0.173648178 \\
    -1 & 0 & 0\end{array}\right] 
$$

In [20]:
N = np.array([[0, -0.173648178, 0.984807753],
              [0, 0.984807753, 0.173648178],
              [-1, 0, 0]])

def func_solve_N(angles):
    zero_matrix = (euler_rotation_matrix(angles[0], angles[1], angles[2]) - N)
    return [zero_matrix[0][1], zero_matrix[1][1], zero_matrix[1][2]]

In [21]:
solution1_N = fsolve(func_solve_M, [0,  1.5,  0])
solution2_N = fsolve(func_solve_M, [-1, -1, -1])
solution3_N = fsolve(func_solve_M, [0, 2, 4])
print(solution1_N)
print(solution2_N)
print(solution3_N)

[0.  1.5 0. ]
[12.02955935  1.29334074 25.42867557]
[0.44174664 1.90461205 5.63908531]


D:\Anaconda\envs\mr_assignment1\lib\site-packages\scipy\optimize\minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)


In [22]:
print(rotation_matrix(solution1_N[0], solution1_N[1], solution1_N[2]))
print(np.isclose(N, rotation_matrix(solution1_N[0], solution1_N[1], solution1_N[2])))

print(rotation_matrix(solution2_N[0], solution2_N[1], solution2_N[2]))
print(np.isclose(N, rotation_matrix(solution2_N[0], solution2_N[1], solution2_N[2])))

print(rotation_matrix(solution3_N[0], solution3_N[1], solution3_N[2]))
print(np.isclose(N, rotation_matrix(solution3_N[0], solution3_N[1], solution3_N[2])))

[[ 0.0707372   0.          0.99749499]
 [ 0.          1.          0.        ]
 [-0.99749499  0.          0.0707372 ]]
[[False False False]
 [ True False False]
 [False  True False]]
[[ 0.26200261 -0.07988122  0.96175549]
 [-0.21984634  0.96542533  0.14007684]
 [-0.93969262 -0.24813892  0.23538236]]
[[False False False]
 [False False False]
 [False False False]]
[[-0.26200261 -0.19674724  0.944799  ]
 [-0.21984634  0.96542533  0.14007684]
 [-0.93969262 -0.1710101  -0.29619812]]
[[False False False]
 [False False False]
 [False False False]]


I have tried 3 initializations and can't seem to get close to a solution.

3. What is a Gimbal lock? 

__Ans:__ While using euler angle sets for 3D rotational transformations, when one of the rotations of the non fixed frame gets alligned due to one of the euler angle rotations with an axis of the fixed frame on which a euler rotation has been already applied,any further rotation about this non fixed frame axis would make the same rotation as that of the alligned fixed frame axis and thus no novel roatation is imposed by rotating about that axis of the non fixed frame. This is termed as Gimbal lock. 
When such a lock occurs, the system ends up losing a degree of freedom (in a sense), as now rotation along these 2 axes changes the orientation of the object in the same way. So now, we have to make a rotation about the 3rd axis to first break out of the gimbal lock, hence increasing the effort for the user. To obtain some desired orientations when in gimbal lock situation, we may need to make rotations along all 3 axes together, which might lead to undesired and skewed trajectories, causing problems for users, like animators.

Reference - https://www.youtube.com/watch?v=zc8b2Jo7mno

4. Show an example where a Gimbal lock occurs and visualize the Gimbal lock on the given bunny point cloud. You have to show the above by **animation** (cube rotating along each axis one by one).
    - *Hint: Use Open3D's non-blocking visualization and discretize the rotation to simulate the animation. For example, if you want to rotate by $30^{\circ}$ around a particular axis, do in increments of $5^{\circ}$ 6 times to make it look like an animation.*

In [23]:
def visualize_gimbal_lock(opc, n):
    v = o3d.visualization.Visualizer()
    v.create_window()
#     n = 100
#     pc = o3d.geometry.TriangleMesh.create_box(0.05,0.05,0.05)
    pc = copy.deepcopy(opc)
    center = pc.get_center()
    v.add_geometry(pc)

    theta = np.pi / n
    
#     coordinate_frame1 = o3d.geometry.TriangleMesh.create_coordinate_frame(size = 0.1, origin = center)
#     v.add_geometry(coordinate_frame1)
    
    cylx = o3d.geometry.TriangleMesh.create_cylinder(radius=0.05, height=0.00101)
    cylx.translate(center)
    cylx.paint_uniform_color([1,0,0])
    cylx.rotate(cylx.get_rotation_matrix_from_xyz([0, np.pi/2, 0]), center)
    v.add_geometry(cylx)
    
    cyly = o3d.geometry.TriangleMesh.create_cylinder(radius=0.06, height=0.001)
    cyly.translate(center)
    cyly.paint_uniform_color([0,1,0])
    cyly.rotate(cyly.get_rotation_matrix_from_xyz([np.pi/2, 0, 0]), center)
    v.add_geometry(cyly)
    
    cylz = o3d.geometry.TriangleMesh.create_cylinder(radius=0.07, height=0.001)
    cylz.translate(center)
    cylz.paint_uniform_color([0,0,1])
    v.add_geometry(cylz)   

    for i in range(n):
        R = rotation_matrix(0, theta/2, 0)
        pc.rotate(R, center = center)
        cylx.rotate(R, center = center)
        cyly.rotate(R, center = center)
        
        v.update_geometry(pc)
        v.update_geometry(cylx)
        v.update_geometry(cyly)
        v.poll_events()
        v.update_renderer()
        
    for i in range(n):
        R = rotation_matrix(0, 0, theta)
        pc.rotate(R, center = center)
        cylx.rotate(R, center = center)
    
        v.update_geometry(pc)
        v.update_geometry(cylx)      
        v.poll_events()
        v.update_renderer()
        
    for i in range(n):
        R = rotation_matrix(0, 0, -theta)
        pc.rotate(R, center = center)
        cylx.rotate(R, center = center)
    
        v.update_geometry(pc)
        v.update_geometry(cylx)      
        v.poll_events()
        v.update_renderer()   
        
    for i in range(n):
        R = rotation_matrix(0, 0, theta)
        pc.rotate(R, center = center)
        cylx.rotate(R, center = center)
        cyly.rotate(R, center = center)
        cylz.rotate(R, center = center)
    
        v.update_geometry(pc)
        v.update_geometry(cylx) 
        v.update_geometry(cyly)  
        v.update_geometry(cylz)      
        v.poll_events()
        v.update_renderer()  
        
    for i in range(n):
        R = rotation_matrix(0, 0, -theta)
        pc.rotate(R, center = center)
        cylx.rotate(R, center = center)
        cyly.rotate(R, center = center)
        cylz.rotate(R, center = center)
    
        v.update_geometry(pc)
        v.update_geometry(cylx) 
        v.update_geometry(cyly)  
        v.update_geometry(cylz)  
        v.poll_events()
        v.update_renderer()  
        
    v.run()
#     v.destroy_window()

In [24]:
bunny_point_cloud = o3d.io.read_point_cloud("results/1/5/bunny.pcd")

In [25]:
visualize_gimbal_lock(bunny_point_cloud, 150)

## b) Quaternions

1. What makes Quaternions popular in graphics? 

__Ans:__ Quaternions do not have the problem of gimbal lock and make the interpolations of the 3D transformations smooth when compared to the jerky interpolations of the euler angles. Also in generating coordinates of the texture maps, quaternions help in just scaling while preserving the angles without getting distorted when a texture is being pasted onto a 3D curved surface.

2. Convert a rotation matrix to quaternion and vice versa. Do not use inbuilt libraries for this question.

In [26]:
def rotation_matrix_to_quaternion(M):
    trace = np.trace(M)
    constant = (1-trace)/4
    
    q0 = np.sqrt((trace+1)/4)
    q1 = np.sqrt(M[0][0]/2 + constant)
    q2 = np.sqrt(M[1][1]/2 + constant)
    q3 = np.sqrt(M[2][2]/2 + constant)
    
    q1 = np.copysign(q1, M[2][1] - M[1][2])
    q2 = np.copysign(q2, M[0][2] - M[2][0])
    q3 = np.copysign(q3, M[1][0] - M[0][1])
    
    return np.array([q0, q1, q2, q3])

In [27]:
def quaternion_to_rotation_matrix(q):
    q0q1 = q[0]*q[1]
    q2q3 = q[2]*q[3]
    
    q0q2 = q[0]*q[2]
    q1q3 = q[1]*q[3]
    
    q0q3 = q[0]*q[3]
    q1q2 = q[1]*q[2]
    
    q0_s = np.square(q[0]) - 0.5
    
    return 2 * np.array([[q0_s + np.square(q[1]), q1q2 - q0q3, q0q2 + q1q3],
                         [q0q3 + q1q2, q0_s + np.square(q[2]), q2q3 - q0q1],
                         [q1q3 - q0q2, q0q1 + q2q3, q0_s + np.square(q[3])]])

In [28]:
R = np.array([[0.1, -0.9487, 0.3],
              [0.9487, 0, -0.3162],
              [0.3, 0.3162, 0.9]])
rotation_matrix_to_quaternion(R)

array([0.70710678, 0.2236068 , 0.        , 0.67082039])

In [29]:
quaternion_to_rotation_matrix(np.array([1/2,-1/2,-1/2,1/2]))

array([[ 0.,  0., -1.],
       [ 1.,  0.,  0.],
       [ 0., -1.,  0.]])

In [30]:
rotation_matrix_to_quaternion(quaternion_to_rotation_matrix(np.array([1/2,-1/2,-1/2,1/2])))

array([ 0.5, -0.5, -0.5,  0.5])

3. Perform matrix multiplication of two $\mathcal{R}_{3 \times 3}$ rotation matrices and perform the same transformation in the quaternion space. Verify if the final transformation obtained in both the cases are the same.

In [31]:
def quaternion_mult(q1,q2):
    qw = q1[0] * q2[0] - q1[1] * q2[1] - q1[2] * q2[2] - q1[3] * q2[3]
    qx = q1[0] * q2[1] + q1[1] * q2[0] + q1[2] * q2[3] - q1[3] * q2[2]
    qy = q1[0] * q2[2] + q1[2] * q2[0] + q1[3] * q2[1] - q1[1] * q2[3]
    qz = q1[0] * q2[3] + q1[3] * q2[0] + q1[1] * q2[2] - q1[2] * q2[1]
    return np.array([qw, qx, qy, qz])

def quaternion_conjugate(q):
    return np.array([q[0], -q[1], -q[2], -q[3]])

def transform_point(q, p):
    return quaternion_mult(quaternion_mult(q, p), quaternion_conjugate(q))

In [32]:
P = np.array([[1],[0],[0]])

R1 = np.array([[0., -1, 0],
               [1, 0, 0],
               [0, 0, 1]])
R2 = np.array([[1, 0, 0],
               [0, 0, -1],
               [0, 1, 0]])
R = np.dot(R1,R2)
P1 = np.dot(R, P)
print(P1)

Pq = np.array([0, 1, 0, 0])
q1 = rotation_matrix_to_quaternion(R1)
q2 = rotation_matrix_to_quaternion(R2)

q = quaternion_mult(q1, q2)
P2q = transform_point(q, Pq)
P2 = np.transpose([P2q[1:]])
print("\n", P2)

[[0.]
 [1.]
 [0.]]

 [[0.]
 [1.]
 [0.]]


As we can see, the operations in both the rotation space and quaternion space return the same target point vector for the same input point vector
<br>
<br>

4. Try to interpolate any 3D model (cube / bunny / not sphere obviously!!) between two rotation matrices and visualize!

The above questions require you to **code your own functions** and **only verify** using inbuilt functions.

In [33]:
def visualize_interpolation_between_rotation_matrices(R1_angles, R2_angles, n, opc):    
    v = o3d.visualization.Visualizer()
    v.create_window()
    
    pc = copy.deepcopy(opc)
    R = rotation_matrix(R1_angles[0], R1_angles[1], R1_angles[2])
    pc.rotate(R, center=[0,0,0])
    v.add_geometry(pc)
    coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size = 0.1)
    v.add_geometry(coordinate_frame)
    theta = (R2_angles - R1_angles) / n
    R = rotation_matrix(theta[0], theta[1], theta[2])
    
    for i in range(n):
        pc.rotate(R, center = [0,0,0])
        v.update_geometry(pc)
        v.poll_events()
        v.update_renderer()
    v.run()
#     v.destroy_window()

In [34]:
bunny_point_cloud = o3d.io.read_point_cloud("results/1/5/bunny.pcd")
visualize_interpolation_between_rotation_matrices(np.array([0,0,0]), np.array([np.pi/2, np.pi/2, 0]), 200, bunny_point_cloud)

## c) Exponential maps (Bonus)

1. What is the idea behind exponential map representation of rotation matrices?

__Ans:__ We can represent the rotation as an a motion where the object travels with an angular velocity w for some theta seconds. This generalizes the rotation to rigid body dynamics.

2. Perform matrix exponentiation and obtain the rotation matrix to rotate a vector $P$ around $\omega$ for $\theta$ seconds.
$$
\omega = \begin{bmatrix}2 \\ 1 \\ 15 \end{bmatrix}
$$

$$
\theta = 4.1364
$$

In [35]:
def get_w_hat(w):
    return np.array([[0, -w[2][0], w[1][0]],
                     [w[2][0], 0, -w[0][0]],
                     [-w[1][0], w[0][0], 0]])

def matrix_exponentiation(w, theta):
    w_hat = get_w_hat(w)
    mod_w = np.linalg.norm(w)
    mod_w_sqr = np.square(mod_w)
#     print(mod_w)
    wt = mod_w * theta
    R = np.identity(3) + np.sin(wt) * w_hat / mod_w  + (1-np.cos(wt)) * np.dot(w_hat, w_hat) / mod_w_sqr
    return R

In [36]:
w = np.array([[2], [1], [15]])
theta = 4.1364
R = matrix_exponentiation(w, theta)
print(R)
# print(np.linalg.det(R))

[[ 0.99506737  0.09902323 -0.00594386]
 [-0.09893593  0.99500189  0.01352466]
 [ 0.00725341 -0.01286989  0.99989087]]


3. Compute the logarithmic map (SO(3) to so(3)) of the rotation matrix to obtain the rotation vector and the angle of rotation
$$
\begin{bmatrix}
0.1 &  -0.9487 & 0.3 \\
0.9487 & 0.  & -0.3162 \\
0.3   &  0.3162  & 0.9 
\end{bmatrix}
$$
You can use inbuilt libraries **only to verify** your results.

In [37]:
def angle_of_rotation(R):
    return np.arccos((np.trace(R)-1)/2)

def rotation_vector(R):
    return 0.5 / np.sin(angle_of_rotation(R)) * np.array([[R[2][1] - R[1][2]], [R[0][2] - R[2][0]], [R[1][0] - R[0][1]]])

# def log_R(R):
#     theta = angle_of_rotation(R)
#     if (theta != 0):
#         return theta / (2*np.sin(theta)) * (R - np.transpose(R))
#     return np.zeros(R.shape)

In [38]:
R = np.array([[0.1, -0.9487, 0.3],
              [0.9487, 0, -0.3162],
              [0.3, 0.3162, 0.9]])

theta = angle_of_rotation(R)
w = rotation_vector(R)
# logR = log_R(R)

print("theta =",theta) 
print("\nw = \n", w)
# print("\nlog(R) = \n", logR)

theta = 1.5707963267948966

w = 
 [[0.3162]
 [0.    ]
 [0.9487]]


In [39]:
# matrix_exponentiation(w, theta)

# 3. Data representations

## a) Octomaps

1. Why is an Octomap memory efficient?

__Ans:__ As an octomap disintegrates the available voxel space into smaller voxels only when there is a conflict in the occupancy of      that voxel space, it hence makes it efficient as we are going in details only when it is required and the extent of details decides the data to be stored. Also multi-resolution voxel grids can be formed.  

2. When do we update an Octomap and why?

__Ans:__ We update an Octomap in dynamic situations as the occupancy of the space keeps changing with time and the probabilities for the voxels need to be rechecked for the confidence in occupancy of them. If not it could even lead to miscalculating the confidences of occupancy of the neighbouring voxels. 

3. When would you likely use an octomap instead of a point cloud?

__Ans:__ Octomap enables sensor data fusion and probabilistic occupancy model can be used to integrate data whereas the pointcloud consumes more memory and also does not differentiate between unmapped area and free space. When there is only need of knowing the occupancy of some space in scenarios like obstacle avoidance,we do not care for the precise location of the surface points of the obstacle as we take care of the errors in the rough surface generated by octomap by having a minimum distance to the surface for avoiding the obstacle as we try to interpolate a smooth transition while avoiding the obstacle.

## b) Signed Distance Functions

1. How do we determine object surfaces using SDF?

__Ans:__ For deciding the cells containing the surface aggregated projected distance and aggregate weight are taken as the parameters of SDF. The rays projected from the sensor will reach the surface passing through the voxels, the voxels which completely intersect the projected rays are considered to be outside the surface (SDF greater than zero) whereas those which let the rays partially intersect are the surface voxels (SDF equal to zero). The distance and weights of these surface voxels are stored.

SDF = 0 => object surface
<br>SDF > 0 => outside
<br>SDF < 0 => inside

2. How do we aggregate views from multiple cameras? (just a general overview is fine)

__Ans:__ From each view we get projected distance which is the difference between distance of the surface from the camera and the distance of the voxel from the camera along the given view.This single distance is initiated with zero weight and is iterated further to aggregate the projected distances obtained from different cameras or different poses of the same camera while updating the aggregate weight by adding up each weight at every iteration.Then finally obtained aggregated distance and weight can be used as parameters of SDF.

3. Which preserves details better? Voxels or SDF? Why?

__Ans:__ SDF preserves details better,as in the case of voxels the confidence in occupancy depends on the confidence in occupancy of the neighbouring voxels whereas in SDF we directly relate every cell with the distance from the surface and the weight associated with it.So it actually tells if the cells are inside or outside the surface and also we can adjust these weights for better results.

4. What’s an advantage of SDF over a point cloud?

__Ans:__ In SDF the algorithm supports for truncation where the cells which are considerably far from the surface can be eliminated.Whereas in pointcloud we would have to store initially all the points and then compute the distances to sample them down.

# References and Resources

1. Gimbal locks and quaternions: https://youtu.be/YF5ZUlKxSgE
2. Exponential map: 
    1. 3 Blue 1 Brown: https://youtu.be/O85OWBJ2ayo
    2. Northwestern Robotics: https://youtu.be/v_KBHaG0mas
3. Bunny ply is taken from: http://graphics.im.ntu.edu.tw/~robin/courses/cg03/model/